export const generateMarkdownReport = (data) => {
  const date = new Date().toLocaleDateString();
  const severity = data.score > 70 ? '🟢 HEALTHY' : data.score > 40 ? '🟡 CAUTION' : '🔴 CRITICAL';

  return `
### 📊 Pulse Audit Report: ${data.full_name}
**Date:** ${date} | **Vitality Score:** ${data.score}/100 (${severity})

#### 🔍 Key Metrics:
- **Activity:** ${data.commitsCount} commits in the last 30 days.
- **Responsiveness:** ${data.avgResolutionDays.toFixed(1)} days avg. resolution time.
- **Backlog:** ${data.openIssues} open issues.
- **Maintenance Risk:** ${data.isHighRisk ? '⚠️ High (Single Contributor dependency)' : '✅ Distributed (Healthy Bus Factor)'}

#### 🛠 Verdict:
${data.score > 70 
  ? "This repository shows strong maintenance signals. Safe for production use." 
  : "Proceed with caution. Maintenance velocity is low or highly centralized."}

*Generated by [Pulse Auditor](https://ahilaadithya.in)*
  `.trim();
};